# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: Rails - Install dependencies and run linters

on:
  push:
  
jobs:
  run-lint:
    runs-on: ubuntu-latest
    
    container:
      image: ruby:2.5.1
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore bundle
        uses: actions/cache@v1
        with:
          path: .vendor
          key: bundle-v1-${{ hasFiles('**/Gemfile.lock')}}
          restore-keys: |
              bundle-v1-${{ hasFiles('**/Gemfile.lock')}}
              
      - name: Save Chae
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle install
     
        

    
    

      # Add or Replace any other Linters here
